### ISSUE TITLE
determine recipe format

### ISSUE THREAD

**Issue by andrewzah** [andrewzah/recipes#2]
* https://github.com/dpapathanasiou/recipebook
  * example usage: https://github.com/dpapathanasiou/recipes
  * http://microformats.org/wiki/hrecipe

**Comment by mboleary** [comment]
Basically, I think where I'm at on the format is that we should have some frontmatter fields for things like the ingredients, but put the actual instructions as markdown.

Here are some formats that I found:
- https://schema.org/Recipe
- https://developers.google.com/search/docs/appearance/structured-data/recipe

I think a subset of those fields would be appropriate. I'll update this when I read through them more closely.

we should develop this with the goal of being decent to generate static websites or latex documents, while also making the markdown files human readable. Personally, I would recommend `yaml` as the frontmatter format, but we can discuss that further

**Comment by mboleary** [comment]
How does something like this look? I took the Stromboli recipe and put it into something inspired by the Google Specs.

[demo_recipe.md](https://github.com/andrewzah/recipes/files/11402430/demo_recipe.md)
